import assert from 'node:assert/strict';
import { openNotificationStore, notificationStore } from '../server/notification-store.mjs';
import { notificationJobs, enqueueNotifications, executeNotification } from '../server/notification-jobs.mjs';
import { enqueueGameReminder, gameReminderEligibility } from '../server/game-reminder-service.mjs';
import { resendTransport } from '../server/resend-transport.mjs';
import { drainNotifications } from '../server/notification-drain.mjs';

if (process.env.FIRESTORE_EMULATOR_HOST !== '127.0.0.1:8180') throw new Error('This test requires the local Firestore emulator.');
assert.throws(() => openNotificationStore('bosse-testing'));
assert.throws(() => notificationStore({ databaseId: '(default)' }));
const first = openNotificationStore('demo-recseason');
const second = openNotificationStore('demo-recseason');
try {
  const [job] = notificationJobs({ kind: 'cancellation', eventId: `storage-test-${Date.now()}`, recipients: ['controlled@example.test'], subject: 'Cancelled', body: 'Synthetic test only.', expiresAt: 86400000 }, 0);
  const results = await Promise.all([enqueueNotifications(first.store, [job]), enqueueNotifications(second.store, [job])]);
  assert.equal(results.reduce((sum, result) => sum + result.created, 0), 1);
  assert.equal(results.reduce((sum, result) => sum + result.existing, 0), 1);
  let sends = 0;
  const worker = store => ({ store, clock: () => 0, isEligible: async () => true, transport: { send: async () => { sends++; return { accepted: true, receipt: 'test-receipt' }; } } });
  const outcomes = await Promise.all([executeNotification(worker(first.store), job.id), executeNotification(worker(second.store), job.id)]);
  assert.equal(sends, 1);
  assert.ok(outcomes.some(result => result.status === 'accepted'));
  await first.db.terminate();
  const saved = await second.store.get(job.id);
  assert.equal(saved.status, 'accepted'); assert.equal(saved.version, 2);
  assert.equal(saved.providerReceipt, 'test-receipt');
  assert.equal((await executeNotification(worker(second.store), job.id)).status, 'accepted');
  assert.equal(sends, 1);
  assert.equal(await second.store.compareAndSet(job.id, 0, { ...job, version: 1, status: 'sending' }), false);
  await assert.rejects(second.store.compareAndSet(job.id, 2, { ...saved, version: 3, recipient: 'different@example.test' }), /immutable/);
  await assert.rejects(second.store.get('../users'), /Invalid/);
  console.log('PASS: durable named-database notification jobs, concurrent enqueue/claim, cross-client persistence, stale-write fencing, and immutable recipients. No email was sent.');
  const db = second.db;
  const put = (collection, id, data) => db.collection(collection).doc(id).set(data);
  await put('users', 'notice-organizer', { role: 'leagueManager' });
  await put('users', 'notice-player', { role: 'player', linkedPlayerId: 'notice-player', email: 'player@example.test' });
  await put('players', 'notice-player', { name: 'Synthetic player', teamId: 'notice-home', archived: false });
  await put('teams', 'notice-home', { name: 'Home' });
  await put('teams', 'notice-away', { name: 'Away' });
  await put('fields', 'notice-field', { name: 'Field' });
  await put('games', 'notice-game', { status: 'scheduled', homeTeamId: 'notice-home', awayTeamId: 'notice-away', fieldId: 'notice-field', homeName: 'Home', awayName: 'Away', fieldName: 'Field', date: '2026-10-08', time: '18:00' });
  const request = { db, store: second.store, verifiedUid: 'notice-organizer', gameId: 'notice-game', now: 0 };
  await assert.rejects(enqueueGameReminder({ ...request, verifiedUid: 'notice-player' }), /organizer/);
  assert.equal((await enqueueGameReminder({ ...request, recipients: ['injected@example.test'], subject: 'Injected subject' })).created, 1);
  assert.equal((await enqueueGameReminder(request)).existing, 1);
  const queued = await db.collection('notificationJobs').where('sourceId', '==', 'notice-game').get();
  const reminder = queued.docs[0].data();
  assert.equal(reminder.recipient, 'player@example.test');
  assert.equal(reminder.subject, 'Game reminder: Home vs Away');
  assert.equal(reminder.requestedBy, 'notice-organizer');
  const eligible = gameReminderEligibility(db);
  assert.equal(await eligible(reminder), true);
  await db.collection('users').doc('notice-organizer').update({ role: 'player' });
  assert.equal(await eligible(reminder), false);
  await db.collection('users').doc('notice-organizer').update({ role: 'leagueManager' });
  await db.collection('users').doc('notice-player').update({ linkedPlayerId: null });
  assert.equal(await eligible(reminder), false);
  await db.collection('users').doc('notice-player').update({ linkedPlayerId: 'notice-player' });
  await db.collection('users').doc('notice-player').update({ emailReminders: false });
  assert.equal(await eligible(reminder), false);
  await db.collection('users').doc('notice-player').update({ emailReminders: true });
  await db.collection('games').doc('notice-game').update({ time: '19:00' });
  assert.equal(await eligible(reminder), false);
  assert.equal((await enqueueGameReminder(request)).created, 1);
  await db.collection('games').doc('notice-game').update({ time: '18:00' });
  await db.collection('players').doc('notice-player').update({ archived: true });
  assert.equal(await eligible(reminder), false);
  await db.collection('players').doc('notice-player').update({ archived: false });
  await db.collection('games').doc('notice-game').update({ status: 'cancelled' });
  assert.equal(await eligible(reminder), false);
  let reminderSends = 0;
  const outcome = await executeNotification({ store: second.store, clock: () => 0, isEligible: eligible, transport: { send: async () => { reminderSends++; return { accepted: true, receipt: 'should-not-send' }; } } }, reminder.id);
  assert.equal(outcome.status, 'suppressed'); assert.equal(reminderSends, 0);
  console.log('PASS: organizer-derived reminder jobs deduplicate and suppress opt-outs, archived players, changed schedules, and cancellations before any provider call.');
  await db.collection('games').doc('notice-game').update({ status: 'scheduled', time: '20:00' });
  assert.equal((await enqueueGameReminder(request)).created, 1);
  const freshJobs = await db.collection('notificationJobs').where('sourceId', '==', 'notice-game').get();
  const fresh = freshJobs.docs.map(row => row.data()).find(value => value.body.includes('20:00'));
  let providerPayload;
  const transport = resendTransport({ apiKey: 're_synthetic_test_only', sender: 'league@example.test', fetcher: async (_url, options) => {
    providerPayload = JSON.parse(options.body);
    return new Response(JSON.stringify({ id: 'synthetic-provider-receipt' }), { status: 200 });
  } });
  assert.equal((await executeNotification({ store: second.store, clock: () => 0, isEligible: eligible, transport }, fresh.id)).status, 'accepted');
  assert.deepEqual(providerPayload.to, ['player@example.test']);
  assert.equal((await second.store.get(fresh.id)).providerReceipt, 'synthetic-provider-receipt');
  console.log('PASS: fresh organizer reminder flows through durable queue, current eligibility, synthetic Resend HTTP, and persisted provider acceptance.');
  const batchJobs = notificationJobs({ kind: 'cancellation', eventId: `batch-${Date.now()}`, recipients: ['due@example.test', 'future@example.test', 'lease@example.test'], subject: 'Batch', body: 'Synthetic', expiresAt: 86400000 }, 0);
  await enqueueNotifications(second.store, batchJobs);
  const dueJob = batchJobs.find(job => job.recipient.startsWith('due@'));
  const future = batchJobs.find(job => job.recipient.startsWith('future@'));
  const lease = batchJobs.find(job => job.recipient.startsWith('lease@'));
  await second.store.compareAndSet(future.id, 0, { ...future, version: 1, status: 'retry', nextAttemptAt: 5000 });
  await second.store.compareAndSet(lease.id, 0, { ...lease, version: 1, status: 'sending', leaseUntil: 1000 });
  const beforeLease = await second.store.due(0, 100);
  assert.ok(beforeLease.includes(dueJob.id));
  assert.ok(!beforeLease.includes(future.id)); assert.ok(!beforeLease.includes(lease.id));
  assert.ok(!beforeLease.includes(fresh.id));
  assert.equal((await second.store.due(1000, 1)).length, 1);
  assert.ok((await second.store.due(1000, 100)).includes(lease.id));
  let batchSends = 0;
  const batchResult = await drainNotifications({ store: second.store, clock: () => 1000, isEligible: async () => true, transport: { send: async () => { batchSends++; return { accepted: true, receipt: 'batch-synthetic' }; } } });
  assert.equal(batchResult.outcomes['needs-review'], 1);
  assert.ok(batchSends >= 1);
  assert.equal((await second.store.get(lease.id)).status, 'needs-review');
  assert.equal((await second.store.get(future.id)).status, 'retry');
  assert.equal((await second.store.due(1000, 100)).length, 0);
  console.log('PASS: bounded due selection excludes future retries and terminal jobs, drains pending work, and reconciles expired leases without resending them.');
} finally {
  await second.db.terminate();
  await first.db.terminate();
}
